"""rename department

Revision ID: 827aac71e2e6
Revises: 2ae9cc1718cc
Create Date: 2025-06-23 12:07:24.441770

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '827aac71e2e6'
down_revision = '2ae9cc1718cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
   op.rename_table('department', 'departments')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('departments', 'department')
    # ### end Alembic commands ###
