"""rename address

Revision ID: b3efb4a47a5c
Revises: 827aac71e2e6
Create Date: 2025-06-23 12:16:11.313075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3efb4a47a5c'
down_revision = '827aac71e2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
     op.alter_column('departments', 'address',  new_column_name='location')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
  op.alter_column('departments', 'location',  new_column_name='address')
    # ### end Alembic commands ###
